### ISSUE TITLE
Retro Replay cartridge blocks REU

### ISSUE THREAD

**Issue by mvdhoning** [mist-devel/c64#15] opened 2024-02-17 15:04 UTC
Using a Retro Replay cartridge blocks acces to a configured REU.
The Retro Replay cartridge allows acces to REU via special memory layout.
The Retro Replay cartridge works together with REU on Vice and on the Turbo Chameleon.
Do not know what black magic Vice and the Turbo Chameleon do to make it work. Hope you can do that magic also.
Fastload and REU at the same time would be nice.

**Comment by gyurco** [comment] 2024-04-17 17:19
The problem is that the cart handling is general, and not all carts are compatible with REU. Must differentiate between cart types to selectively enable/disable REU.

**Comment by gyurco** [comment] 2024-08-17 12:52
Released in 240814

**Closed as completed by gyurco** 2024-08-17 12:52 UTC
